### ISSUE TITLE
Need a way to pass --shell-wrapper parater with Start-AIShell to keep custom config to wrap Start-AIShell

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/ProjectMercury#197]
### Summary of the new feature / enhancement

Currently there is no way for me to change the configs in the options for `--shell-wrapper` config file (i.e banner, title, description etc) with `Start-AIShell`. We need some way to pass this information to the aish executable that Start-AIShell calls from.

### Proposed technical implementation details (optional)

`Atart-AIShell -Path .\aish.exe -ShellWrapper "C:\Users\stevenbucher\.aish\shellwrapperconfig.json"`

**Comment by daxian-dbw** [comment]
I don't think `--shell-wrapper` should be exposed in `Start-AIShell`. `Start-AIShell` is facing the end users, who don't know and shouldn't need to know `--shell-wrapper`. For "Copilot for client tools", they will not be calling `Start-AIShell` directly, but will need to do things similar to `Start-AIShell` -- establish the named pipe, then call `aish --channel <xxx> --shell-wrapper <yyy>`.

**Comment by daxian-dbw** [comment]
BTW, will this issue supersede https://github.com/PowerShell/ProjectMercury/issues/120?
