### ISSUE TITLE
Change `/` chat command syntax to be `/<action> <resource>` instead of `/<resource> <action>`

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/ProjectMercury#198]
### Summary of the new feature / enhancement

Currently we have an inconsistency in `/` commands as far as syntax structure. We have action commands like `/like`, `/retry` and `/refresh` but also have commands that start with the resource like `/code` and `/agent`. For consistency and ease of future expansion we should consider switching to a more <action> <resource> grammar. 

### Proposed technical implementation details (optional)

Switch to `/<action> <resource>` format. This means changing exsisting ones like `/code copy`. Some proposed ones I can thing of are:

 | Command      | Description      |
| ------------- | ------------- |
| /copy  | Copies entire response + code |
| /copy code <n> | Copies code only if n is not specified and n step if specified |
| /copy chat  | Copies the chat only and not the code |
| /save  | Saves entire response + code |
| /save code <n> | Saves code only if n is not specified and n step if specified |
| /save chat  | Saves the chat only and not the code |
| /edit  | Opens the entire response in users default editor |
| /edit code <n> | Opens specified code block or whole block in users default editor |
| /edit chat  | Opens just the chat contents in users default editor |
| /config  | Opens the `config.json` file in the `.aish` folder |
| /config <agent> | Opens specified agents config file in users default editor |
| /use <agent>  | Switches users current agent |
| /list | Lists users current agents |
| /replace param  | Goes through user input form for editing placeholder parameter values |
| /post | Posts just the code to the working terminal |

Very open to ideas and suggestions on any of these commands, I hope to have an open discussion on this!

**Comment by daxian-dbw** [comment]
In my opinion, there are 2 kinds of commands and we should use different syntax for them respectively:
- An action to take
- Manage a resource

For the 1st, naturally it should be a verb.
For the 2nd, I think it should be `/<name-of-resource> <action>`, just like Az CLI commands, e.g. `vm create`

**Comment by StevenBucher98** [comment]
One big problem is that for agents creating their own commands like the `/gpt` command would not work in this case.
