### ISSUE TITLE
Unable to ask a question, getting a object reference not found

### ISSUE THREAD

**Issue by maikvandergaag** [PowerShell/ProjectMercury#290]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When asking a question to the azure agent we get the below response:

![image](https://github.com/user-attachments/assets/e957e5e4-1cca-4570-985c-0853ceb5dc5a)

### Expected behavior

```console
Answer to my question
```

### Actual behavior

```console
Getting a error
```

### Error details

```console
See screenshot included in the description
```

### Environment data

```PowerShell
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26120
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Using AIShell MVP Build version
```

### Version

MVP Build

**Comment by daxian-dbw** [comment]
@maikvandergaag Thanks for reporting the issue!

**Comment by maikvandergaag** [comment]
No problem. Do I need to install / download a new version to check it out further

**Comment by daxian-dbw** [comment]
The error response from Azure Copilot is out of our control, but I think I fixed the null reference exception (also added a telemetry when receiving an error response). To get a newer version you will need to clone the repo and build AIShell from the main branch. If you could do that, that'd awesome. If not, it's okay, just keep using the version you have and report any issues that you ran into. Thank you again for your help!
